name: Android Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Gradle
        uses: gradle/gradle-build-action@v2

      # ✅ Step: Re-generate Gradle Wrapper
      - name: Generate Gradle Wrapper
        run: |
          rm -rf gradle/wrapper/gradle-wrapper.jar
          gradle wrapper --gradle-version 8.7

      # ✅ Step: Build Debug APK
      - name: Build Debug APK
        run: ./gradlew assembleDebug

      # ✅ Step: Upload APK
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk
